### ISSUE TITLE
Design bai scriptMode schanges in descriptor

### ISSUE THREAD

**Issue by stsukrov** [awslabs/benchmark-ai#276]
Due to foreseen customer request:

```toml
script="launch.py" #Or some python package with setup.py?
requirments="lib1/lib2/lib3"
```
