### ISSUE TITLE
Benchmark pod should request GPUs

### ISSUE THREAD

**Issue by marcoabreu** [awslabs/benchmark-ai#483]
Right now, a benchmark pod simply uses the GPUs that are available on the host without them actually being assigned. This results in per-pod-GPU metrics and similar information that are pod-specific to not cover anything GPU-related since from the perspective of Kubernetes, the pod does actually not have access to a GPU resource.

In case of a GPU instance, we should add the GPU request. In ``src/transpiler/templates/job_single_node.yaml``, for example, the ``requests.limit`` entry should have the ``nvidia.com/gpu`` entry. The value should then be dynamic that it matches the number of GPUs available. We can parse https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-west-2/index.json for example, to get the number of available GPUs for an instance type.

Here's how I added the entry:
```
      containers:
      - name: benchmark
        image: {descriptor.docker_image}
        command: []
        args: []
        resources:
          limits:
             nvidia.com/gpu: 4
```
